In [1]:
# EDA Packages
import pandas as pd
import numpy as np
from pandas import DataFrame

In [2]:
# ML Packages For Vectorization of Text For Feature Extraction/TfidVectorizer is convert text input to feature vectors
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
# Visualization Packages
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df1 = pd.read_csv("Test_data10.csv")

In [5]:
frames = [df1]

In [6]:
df_merged = pd.concat(frames)

In [7]:
df_merged.shape

(9, 8)

In [8]:
df_merged.columns

Index(['Date', 'Transaction_Value', 'Transaction_Type', 'Gender', 'Age',
       'Occupation', 'Industry', 'Repitive'],
      dtype='object')

In [9]:
df_merged.dtypes

Date                 object
Transaction_Value     int64
Transaction_Type     object
Gender               object
Age                   int64
Occupation           object
Industry             object
Repitive              int64
dtype: object

In [10]:
df_merged.isnull().isnull().sum()

Date                 0
Transaction_Value    0
Transaction_Type     0
Gender               0
Age                  0
Occupation           0
Industry             0
Repitive             0
dtype: int64

In [11]:
df_merged_data = df_merged[["Date","Transaction_Type","Gender","Age","Industry","Repitive"]]

In [12]:
df_merged_data.columns

Index(['Date', 'Transaction_Type', 'Gender', 'Age', 'Industry', 'Repitive'], dtype='object')

In [13]:
df_merged_data['StringAge'] = df_merged_data['Age'].astype(str)

In [14]:
df_merged_data['combine1'] = df_merged_data[['Date','Transaction_Type','Gender', 'StringAge','Industry']].agg('/'.join,axis=1)
df_merged_data['combine1']

0                 29/02/2020 02:56/IBG/M/22/Plantation
1         14/02/2020 23:04/DuitNow/F/26/Transportation
2    10/05/2020 16:53/Instant Transfer/M/37/Technology
3                 29/01/2020 18:07/IBG/M/22/Plantation
4         14/01/2020 05:49/DuitNow/F/26/Transportation
5         03/04/2020 17:56/Instant Transfer/M/62/Sport
6        15/03/2020 08:42/DuitNow/F/33/Food & Beverage
7                     16/01/2020 10:46/IBG/M/57/Health
8    15/04/2020 10:20/Instant Transfer/F/33/Food & ...
Name: combine1, dtype: object

In [15]:
df_x = df_merged_data['combine1']
df_y = df_merged_data['Repitive']

In [16]:
cv = CountVectorizer()
ex = cv.fit_transform(["DuitNow"])

In [17]:
ex.toarray()

array([[1]], dtype=int64)

In [18]:
cv.get_feature_names()

['duitnow']

In [19]:
testdata = df_x
cv = CountVectorizer()
X = cv.fit_transform(testdata) # Fit the Data

In [20]:
X.toarray()

array([[0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 

In [21]:
cv.get_feature_names()

['01',
 '02',
 '03',
 '04',
 '05',
 '07',
 '08',
 '10',
 '14',
 '15',
 '16',
 '17',
 '18',
 '20',
 '2020',
 '22',
 '23',
 '26',
 '29',
 '33',
 '37',
 '42',
 '46',
 '49',
 '53',
 '56',
 '57',
 '62',
 'beverage',
 'duitnow',
 'food',
 'health',
 'ibg',
 'instant',
 'plantation',
 'sport',
 'technology',
 'transfer',
 'transportation']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, df_y, test_size=0.33, random_state=2)

In [24]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.6666666666666666

In [25]:
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 66.66666666666666 %


In [26]:
clf.predict(X_test)

array([0, 1, 1], dtype=int64)

In [27]:
comment = ["Instant Transfer"]
vect = cv.transform(comment).toarray()

In [28]:
clf.predict(vect)

array([0], dtype=int64)

In [29]:
class_dict = {'OneTime':0,'Repitive':1}

In [30]:
class_dict.values()

dict_values([0, 1])

In [31]:
if clf.predict(vect) == 1:
    print("Repetitive")
else:
    print("OneTime")

OneTime
